# This file was generated by GoReleaser. DO NOT EDIT.
cask "blf" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Darwin_x86_64.tar.gz"
      sha256 "de794f464f60c433da58a4c1e41cd199e7d7a6585ffdbb1371e0d9de9f8c93bc"
    end
    on_arm do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Darwin_arm64.tar.gz"
      sha256 "43527fc01335409a1924dc1de6b02f13e46f8d27294d04a9907810f6558b7cc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Linux_x86_64.tar.gz"
      sha256 "dc6f5ff958fa8d8bd6712b76903fc35608f541a2525c2af8566dd02925b096ab"
    end
    on_arm do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Linux_arm64.tar.gz"
      sha256 "6bb900f5d1d208da572648f4060ccc037f83a2331868b1712b8ff52fcc4db3ca"
    end
  end

  name "blf"
  desc "Blazingly fast misc CLI utilities"
  homepage "https://github.com/elentok/blf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blf"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blf"]
      end
    end
  end

  # No zap stanza required

end
