# This file was generated by GoReleaser. DO NOT EDIT.
cask "blf" do
  name "blf"
  desc "Blazingly fast misc CLI utilities"
  homepage "https://github.com/elentok/blf"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blf"

  on_macos do
    on_intel do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Darwin_x86_64.tar.gz"
      sha256 "e53a9476e2f426071a92966501fb9790149a8b970e9e33786154750276ba8bad"
    end
    on_arm do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Darwin_arm64.tar.gz"
      sha256 "dd0a4aa6e7696b45a32abce8a709f02e96f30c9a793f0227af2343aa81c529eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Linux_x86_64.tar.gz"
      sha256 "6c43d9b548915da827048f4626a9a322123dc929b5b48ec763239db94a165175"
    end
    on_arm do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Linux_arm64.tar.gz"
      sha256 "5e00396e2d975545e6c3e2cb274f07ebbdb14afd9b3f2be61aa143715d0f2e02"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blf"]
      end
    end
  end

  # No zap stanza required
end
