# This file was generated by GoReleaser. DO NOT EDIT.
cask "blf" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Darwin_x86_64.tar.gz"
      sha256 "f2048d9f9f86ddeb08865846b452fcdcf6e0879bde96b0228e08d98465f54012"
    end
    on_arm do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Darwin_arm64.tar.gz"
      sha256 "7fe840a088587bc78d578c4a74262cbbb2100ea5570725e88a5df4567509e50c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Linux_x86_64.tar.gz"
      sha256 "3785cad9022cfdf97dfdee72ce962d07a35fc1da9a15ad80b98dd7285993795a"
    end
    on_arm do
      url "https://github.com/elentok/blf/releases/download/v#{version}/blf_Linux_arm64.tar.gz"
      sha256 "c31d0fd911c3ec6b977514534de3306fdb38e57eb015cd388a45789a2526bb80"
    end
  end

  name "blf"
  desc "Blazingly fast misc CLI utilities"
  homepage "https://github.com/elentok/blf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blf"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blf"]
      end
    end
  end

  # No zap stanza required

end
