# This file was generated by GoReleaser. DO NOT EDIT.
cask "colr" do
  name "colr"
  desc "Interactive terminal color editor."
  homepage "https://github.com/elentok/colr"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "colr"

  on_macos do
    on_intel do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Darwin_x86_64.tar.gz"
      sha256 "96f5677deebb08206e1c803575eaadee19d1d24283df88a412726ddbe49fbb35"
    end
    on_arm do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Darwin_arm64.tar.gz"
      sha256 "9565d4e94bc7b88f0bb3abb19bb02e7639da336fd189d89680d7bc4c082f5376"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Linux_x86_64.tar.gz"
      sha256 "baae02c67780f437ae64d9ed71ad12d1fc339f0e202c4f7e8d7134525dd1565c"
    end
    on_arm do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Linux_arm64.tar.gz"
      sha256 "f79dd13d7c5ff3dcf4ef968935718b6c0add4c34de5c570b1ff7998021fadefa"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/colr"]
      end
    end
  end

  # No zap stanza required
end
