# This file was generated by GoReleaser. DO NOT EDIT.
cask "colr" do
  name "colr"
  desc "Interactive terminal color editor."
  homepage "https://github.com/elentok/colr"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "colr"

  on_macos do
    on_intel do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Darwin_x86_64.tar.gz"
      sha256 "90194683882d20ea20021ecef0d459a5e96213e22b06a801bed6902e5d609a71"
    end
    on_arm do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Darwin_arm64.tar.gz"
      sha256 "97a73bde6622e4048a01c5d868e08295f0c3b1dfe39cdb6fcbe96c9b1947c6c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Linux_x86_64.tar.gz"
      sha256 "36ea94033edf5699668d6ebd5b990fb15ec2f58733e34b901b177ccfba16a54d"
    end
    on_arm do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Linux_arm64.tar.gz"
      sha256 "137079ed03bd9e0fa090fb3cec6142c18d783231396dd95e6c4a1f77ef8a509a"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/colr"]
      end
    end
  end

  # No zap stanza required
end
