# This file was generated by GoReleaser. DO NOT EDIT.
cask "colr" do
  name "colr"
  desc "Interactive terminal color editor."
  homepage "https://github.com/elentok/colr"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "colr"

  on_macos do
    on_intel do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Darwin_x86_64.tar.gz"
      sha256 "be4fe510ebf1c267d71e730686acc8b18f4ff8c6948f418ed6108130272622ee"
    end
    on_arm do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Darwin_arm64.tar.gz"
      sha256 "6d39ee368126a869e094b096940e79a08a852c64afc5fa3c49cf90f747177e12"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Linux_x86_64.tar.gz"
      sha256 "3fc1ba3ed017f7b9cec27fb00d38b6ad27f83654db7d42d1ae7bc981c609ae57"
    end
    on_arm do
      url "https://github.com/elentok/colr/releases/download/v#{version}/colr_Linux_arm64.tar.gz"
      sha256 "e59d75149c2ab7d0fa45e9972c118eae29475a9f4dcd25422dce2506c1dded28"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/colr"]
      end
    end
  end

  # No zap stanza required
end
