# This file was generated by GoReleaser. DO NOT EDIT.
cask "dff" do
  desc "Prettifier for the `df` (diskfree) command in Go."
  homepage "https://github.com/elentok/dff/"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dff"

  on_macos do
    on_intel do
      url "https://github.com/elentok/dff/releases/download/v0.1.1/dff_Darwin_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.1",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "0a25b011378bddf294340e174b7be81186088abe4be389db256cf04c5866980e"
    end
    on_arm do
      url "https://github.com/elentok/dff/releases/download/v0.1.1/dff_Darwin_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.1",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "98644c414b10fb10e5388aa48f6420d0a07941a6366611b70db2148668bc554a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/dff/releases/download/v0.1.1/dff_Linux_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.1",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "14ccaee4804e51b384c4582aa4e7d8a335a3c2414448d3233eafe09643ef96ad"
    end
    on_arm do
      url "https://github.com/elentok/dff/releases/download/v0.1.1/dff_Linux_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.1",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "63fe3d3bf41fad9517f1d55523369ec870bb49fe30309473b82bdcdf838f7809"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dff"]
      end
    end
  end

  # No zap stanza required
end
