# This file was generated by GoReleaser. DO NOT EDIT.
cask "dff" do
  desc "Prettifier for the `df` (diskfree) command in Go."
  homepage "https://github.com/elentok/dff/"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dff"

  on_macos do
    on_intel do
      url "https://github.com/elentok/dff/releases/download/v0.0.7/dff_Darwin_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "d736f3faa7dde1746766eaf7e1b0b2ed0c7e3304b5a6c5de0673a780fcab3a75"
    end
    on_arm do
      url "https://github.com/elentok/dff/releases/download/v0.0.7/dff_Darwin_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "67f1013fc986e83c96b4d41b00062a59acebd9329324fd44d251118eb7ba0a53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/dff/releases/download/v0.0.7/dff_Linux_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "63cf8eb66523a66eb10a374eae5d4af10aa69b97705550552ea127b59f5cb5d5"
    end
    on_arm do
      url "https://github.com/elentok/dff/releases/download/v0.0.7/dff_Linux_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "359ebd936d90a15fb0e8c7346113e814a4f689b903e5f6e037a919449e89c396"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dff"]
    end
  end

  # No zap stanza required
end
