# This file was generated by GoReleaser. DO NOT EDIT.
cask "dff" do
  desc "Prettifier for the `df` (diskfree) command in Go."
  homepage "https://github.com/elentok/dff/"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dff"

  on_macos do
    on_intel do
      url "https://github.com/elentok/dff/releases/download/v0.0.8/dff_Darwin_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "fb69f145d2a176368a15b81227cfd7c560179a9760f5dbb2e4cce39ed597fc63"
    end
    on_arm do
      url "https://github.com/elentok/dff/releases/download/v0.0.8/dff_Darwin_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "d047b0a1983588041942a87365099ff0a3d8ca4b6ef45ef92dabf5fa01f38290"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/dff/releases/download/v0.0.8/dff_Linux_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "12032182a404ec2680c949eefb739288b81b2e501204d61d27f82ab3add07dd1"
    end
    on_arm do
      url "https://github.com/elentok/dff/releases/download/v0.0.8/dff_Linux_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ],
        user_agent: "MyApp/1.0 (macOS)",
        data: {
          "format" => "dmg",
          "platform" => "mac",
        }
      sha256 "94e4d268d9c92d63101ba7ecf5cb0aa3ba82e86fa04ed28861a6d46aa8804037"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dff"]
      end
    end
  end

  # No zap stanza required
end
