# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfl" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Darwin_x86_64.tar.gz"
      sha256 "be36deef622a8c6b1b1a754963b8869c525e30c60fbc8f104557c3a2fbf40022"
    end
    on_arm do
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Darwin_arm64.tar.gz"
      sha256 "054db6abf98d2db214cbee929c1ea996f9d90679ce35de4f5e3f26a0c167b9b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Linux_x86_64.tar.gz"
      sha256 "15c7fbcfa8e7d341be73e27a926309aba2a1593c79a38a014bbc7bf6268f4756"
    end
    on_arm do
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Linux_arm64.tar.gz"
      sha256 "85a7c6699c983e84ab8dd1073f4019485669ee6d032710a02ec2904de91074f0"
    end
  end

  name "dfl"
  desc "Go-based dotfiles setup and install runtime."
  homepage "https://github.com/elentok/dfl/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfl"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dfl"]
      end
    end
  end

  # No zap stanza required

end
