# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfl" do
  version "0.2.9"

  on_macos do
    on_intel do
      sha256 "187264545736c44271452fb1a615456e6f514ebab1a47d00d49015683f68f6ec"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "34cdf9c5daaf3275ad0c2e2ff65260de79f1544aba6d1c00bc6e5f40e1471a2e"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9609d06126c1a994f3c90faf779634b7896e98c00a9f7eba569aaae14815b72b"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2820e37b4c50cb3675af2a6fb130f6cfa9aca5db8db9e5c08d69ce4d54b6043b"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Linux_arm64.tar.gz"
    end
  end

  name "dfl"
  desc "Go-based dotfiles setup and install runtime."
  homepage "https://github.com/elentok/dfl/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfl"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dfl"]
      end
    end
  end

  # No zap stanza required

end
