# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfl" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "6c8222bbb5b9eb17ef8bc7ad6a141c7275c88185f267c9c70f086d703fc51b47"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f42b3c5a14c5efd91c58db33ecc1d0799afe15f01a4fde4a9768eb05093b8b9e"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec0645ab5804421e394e349185928b1911140153669747a1275b3e5f1c876e30"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3814eda713cfede048676513eb5161e9ee49654e8ab8651ed9daf4fb4ee15767"
      url "https://github.com/elentok/dfl/releases/download/v#{version}/dfl_Linux_arm64.tar.gz"
    end
  end

  name "dfl"
  desc "Go-based dotfiles setup and install runtime."
  homepage "https://github.com/elentok/dfl/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfl"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dfl"]
      end
    end
  end

  # No zap stanza required

end
