# This file was generated by GoReleaser. DO NOT EDIT.
cask "gx" do
  version "0.22.1"

  on_macos do
    on_intel do
      sha256 "cfb2ef59f22401758c813f7f1912195e848aae32987a8d6b346e46a2f7e4bec4"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "29156e48e2161cc08c7d9316eacd60d96b7b6f15b4ba0eaceaf357f0113a2953"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "385ba763da3a57ef7cc7f170b70926829ff98ea15147733e5a83fc9582689b02"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "44ac327d91f96298153472a668c096db2f2e81c288fb77ca833956d93be3d658"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Linux_arm64.tar.gz"
    end
  end

  name "gx"
  desc "Interactive TUI and CLI helpers for git."
  homepage "https://github.com/elentok/git-helpers/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gx"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gx"]
      end
    end
  end

  # No zap stanza required

end
