# This file was generated by GoReleaser. DO NOT EDIT.
cask "gx" do
  version "0.12.7"

  on_macos do
    on_intel do
      sha256 "faade6797055957d582a596c4bb1a70cfb7f172281a8d9e2e276e9389bba4d5b"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bbc1dadbb9d8fb45877b3fe70dcb6cd0b34e8a89e7c3bee20b338137576913ce"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80f77bbd520bc228a46d7ff0e72930eedeeb1a089fa3662ce82373f771948c73"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2a630b28ca48b0d86df46cb9fc57a558b4c006bbc621d5b90410279c18bd02ba"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Linux_arm64.tar.gz"
    end
  end

  name "gx"
  desc "Interactive TUI and CLI helpers for git."
  homepage "https://github.com/elentok/git-helpers/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gx"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gx"]
      end
    end
  end

  # No zap stanza required

end
