# This file was generated by GoReleaser. DO NOT EDIT.
cask "gx" do
  version "0.28.6"

  on_macos do
    on_intel do
      sha256 "89d72b8bcd9a3d2ed56965778533858b663f39492bca2758d9af9309520c82aa"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8709ca7239cb239df252fbe5a3d9316941c8402e1cb5a8441ea42102eb0667a8"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef40644990eb593ca6b80ee3b7cf9afb222bbd7b3fcf67ee318812502b5ef74d"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "976be4578eb3f8891f2095b2d296996f409280384b73c926e3c64909ef4b1aa9"
      url "https://github.com/elentok/git-helpers/releases/download/v#{version}/gx_Linux_arm64.tar.gz"
    end
  end

  name "gx"
  desc "Interactive TUI and CLI helpers for git."
  homepage "https://github.com/elentok/git-helpers/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gx"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gx"]
      end
    end
  end

  # No zap stanza required

end
