# This file was generated by GoReleaser. DO NOT EDIT.
cask "qmkmd" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c009bf22505bf929be0d97e572cb6b1310f5c681f1d44c6070e669d69f2b1e8a"
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8c4843fd841a98d706374d6aba50ca8f9943d08ec462745328b6ff119307bb3d"
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fdcf845f5bde6ee9097ec7928585ebacbcaf681eaa5fdc4d755082b16c920519"
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a34908ca1b7347d5902cff82ab8210b207cdb1e2b9e344b26dc5c85bb8849d5d"
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Linux_arm64.tar.gz"
    end
  end

  name "qmkmd"
  desc "Build, format, and copy QMK keyboard layouts written in Markdown."
  homepage "https://github.com/elentok/qmkmd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qmkmd"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmkmd"]
      end
    end
  end

  # No zap stanza required

end
