# This file was generated by GoReleaser. DO NOT EDIT.
cask "qmkmd" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Darwin_x86_64.tar.gz"
      sha256 "f70d40087c324b2a2f2a957e78c0aa5b64d9f36e6c3f059630a3e4884b9ab39d"
    end
    on_arm do
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Darwin_arm64.tar.gz"
      sha256 "130376281018ea06510d1360c65275aa9f4667f8a1a29c995284279984c90654"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Linux_x86_64.tar.gz"
      sha256 "d340dc68e377c9ba2cdfe1879f157604a264d6cece277bf116c0876e20f4f0c0"
    end
    on_arm do
      url "https://github.com/elentok/qmkmd/releases/download/v#{version}/qmkmd_Linux_arm64.tar.gz"
      sha256 "eda070a91031fb4c6b398d021631cccc2ab694bc22f7359690c4e6af6d684b9c"
    end
  end

  name "qmkmd"
  desc "Build, format, and copy QMK keyboard layouts written in Markdown."
  homepage "https://github.com/elentok/qmkmd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qmkmd"

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmkmd"]
      end
    end
  end

  # No zap stanza required

end
